### PR TITLE
update to new glossary standard

### PR DESCRIPTION
**Pull request by drgrigg**
I gave up on the fixgloss branch. Can we commit this branch instead?

### CODE REVIEW

**Comment by drgrigg** [comment]
Ugh, no. Lint now throwing errors. I give up! For today at least.

**Comment by acabal** [comment]
This looks like it's probably fine, you can reopen it and I'll fix whatever's going on

**Comment by drgrigg** [comment]
Time for me to learn more about Git!

**Comment by acabal** [comment]
Lint is fine, you probably didn't update to 1.6.0 yet or you ran lint on the branch before rebasing it on master. I'll merge this in, thanks!

**Comment by acabal** [comment]
How do you feel about working on the Darwin glossary next?

**Comment by drgrigg** [comment]
Sure, that's fine.

**Pull request merged**
